#!/bin/sh
# ============ General ============
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#665c54"
bspc config presel_feedback_color   "#7c6f64"

feh --bg-fill ~/dotfiles/wallpaper.jpg  &
~/.bin/betterlockscreen -u ~/dotfiles/wallpaper.jpg -b 1.0 &

# ============ Monitors ============
if [[ -x $HOME/.config/bspwm/monitors ]]; then
    source $HOME/.config/bspwm/monitors
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# ============ Services ============
pkill sxhkd 2> /dev/null; sxhkd &
pkill dunst 2> /dev/null; dunst &
pkill blurwal 2> /dev/null; (sleep 3;blurwal -m 1 --backend feh &> /tmp/.blurwal ) &
pkill compton 2> /dev/null; compton --config $HOME/.config/compton/compton.conf &
pkill udiskie 2> /dev/null; udiskie -t &
pkill nm-applet 2> /dev/null; nm-applet &
pgrep nextcloud > /dev/null || nextcloud --background &

# Kill and launch polybar
$HOME/.config/polybar/launch.sh

# ============ Rules ============
bspc rule -a Yad state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Steam state=floating follow=on
