#!/bin/bash
# ============ General ============
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#d65d0e"
bspc config presel_feedback_color   "#7c6f64"

feh --bg-fill ~/dotfiles/wallpaper.jpg  &
~/.bin/betterlockscreen -u ~/dotfiles/wallpaper.jpg -b 1.0 &

xset r rate 250 50
xsetroot -cursor_name left_ptr

# ============ Monitors ============
case $(hostname -s) in
    fedora-desktop)
        xrandr --output DP-0 --mode 2560x1440 --rate 144
        xrandr --output DVI-D-0 --mode 1920x1080 --rate 144
        bspc monitor DP-0 -d 1 2 3 4 mail
        bspc monitor DVI-D-0 -d 6 7 8 9 discord
        ;;
    *)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 0
        ;;
esac

# ============ Rules ============
bspc rule -a Yad state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Steam state=floating follow=on
bspc rule -a Blueman-manager state=floating follow=on
bspc rule -a Thunderbird desktop=mail
bspc rule -a discord desktop=discord

# ============ Services ============
pkill sxhkd 2> /dev/null; sxhkd -m 1 &
pkill dunst 2> /dev/null; dunst &
pkill blurwal 2> /dev/null; (sleep 3;blurwal -m 1 --backend feh &> /tmp/.blurwal ) &
pkill compton 2> /dev/null; compton --config $HOME/.config/compton/compton.conf &
pkill udiskie 2> /dev/null; udiskie -t &
pkill nm-applet 2> /dev/null; nm-applet &
pkill xautolock 2> /dev/null; xautolock -time 10 -locker '~/.bin/betterlockscreen -l blur' &
pgrep nextcloud > /dev/null || nextcloud --background 2> /dev/null &
pgrep thunderbird > /dev/null || thunderbird 2> /dev/null &
pgrep discord > /dev/null || discord 2> /dev/null &

# So we dont switch to this desktop on startup
bspc rule -a Thunderbird desktop=mail follow=on
bspc rule -a discord desktop=discord follow=on

# Kill and launch polybar
$HOME/.config/polybar/launch.sh &
